name: PostProc Mobirise Site
on: [push]
jobs:
  Add-MLH-Banner:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Remove Mobirise Footer
        uses: jacobtomlinson/gha-find-replace@2.0.0
        with:
          find: "display: flex;"
          replace: "background-color: #232323;pointer-events: none;display: flex;"
          regex: false
          include: "index.html"
      - name: Setup git and commit remove footer
        run: |
          git config --global user.name 'matticoli'
          git config --global user.email 'matticoli@users.noreply.github.com'
          git commit -am "Remove mobirise footer"
          git push